"""remove essay_score from testpaperresult

Revision ID: 72e4c60d554a
Revises: e60bffadffe3
Create Date: 2025-07-28 17:55:37.189638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e4c60d554a'
down_revision: Union[str, None] = 'e60bffadffe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
