"""Add name to TestPaper

Revision ID: 9f78da141d4e
Revises: a5752fb8e516
Create Date: 2025-07-19 14:32:17.049568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f78da141d4e'
down_revision: Union[str, None] = 'a5752fb8e516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_paper_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=True),
    sa.Column('user_answers', sa.JSON(), nullable=True),
    sa.Column('grading_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_paper_results_id'), 'test_paper_results', ['id'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.add_column('test_papers', sa.Column('name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_test_papers_id'), 'test_papers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_papers_id'), table_name='test_papers')
    op.drop_column('test_papers', 'name')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_test_paper_results_id'), table_name='test_paper_results')
    op.drop_table('test_paper_results')
    # ### end Alembic commands ###
