"""Add question_feedbacks to TestPaperResult

Revision ID: a12cb63cdbb2
Revises: 9f78da141d4e
Create Date: 2025-07-21 21:29:45.451136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12cb63cdbb2'
down_revision: Union[str, None] = '9f78da141d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_feedbacks_id', table_name='question_feedbacks')
    op.drop_table('question_feedbacks')
    op.add_column('test_paper_results', sa.Column('question_feedbacks', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_paper_results', 'question_feedbacks')
    op.create_table('question_feedbacks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('result_id', sa.INTEGER(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.Column('feedback', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['test_paper_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_feedbacks_id', 'question_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###
