"""Add config and generation_prompt to test_papers

Revision ID: dd9ed1c31122
Revises: 72e4c60d554a
Create Date: 2025-07-31 12:41:39.113370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9ed1c31122'
down_revision: Union[str, None] = '72e4c60d554a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_papers', sa.Column('config', sa.JSON(), nullable=True))
    op.add_column('test_papers', sa.Column('generation_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_papers', 'generation_prompt')
    op.drop_column('test_papers', 'config')
    # ### end Alembic commands ###
