"""Initial migration

Revision ID: e60bffadffe3
Revises: 
Create Date: 2025-07-28 17:54:57.606615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e60bffadffe3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('total_objective_questions', sa.Integer(), nullable=True),
    sa.Column('total_essay_questions', sa.Integer(), nullable=True),
    sa.Column('source_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_papers_created_at'), 'test_papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_papers_id'), 'test_papers', ['id'], unique=False)
    op.create_index(op.f('ix_test_papers_name'), 'test_papers', ['name'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('stem', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_table('test_paper_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_paper_id', sa.Integer(), nullable=True),
    sa.Column('user_answers', sa.JSON(), nullable=True),
    sa.Column('grading_results', sa.JSON(), nullable=True),
    sa.Column('correct_objective_questions', sa.Integer(), nullable=True),
    sa.Column('overall_feedback', sa.Text(), nullable=True),
    sa.Column('question_feedbacks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_paper_id'], ['test_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_paper_results_created_at'), 'test_paper_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_test_paper_results_id'), 'test_paper_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_paper_results_id'), table_name='test_paper_results')
    op.drop_index(op.f('ix_test_paper_results_created_at'), table_name='test_paper_results')
    op.drop_table('test_paper_results')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_test_papers_name'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_id'), table_name='test_papers')
    op.drop_index(op.f('ix_test_papers_created_at'), table_name='test_papers')
    op.drop_table('test_papers')
    # ### end Alembic commands ###
